### GET ALL
GET http://localhost:8080/users

###
GET http://localhost:8080/users/3

### 
GET http://localhost:8080/users/role/SUPER_ADMIN

### 
GET http://localhost:8080/users/search/name?name=dd
###POST 

POST http://localhost:8080/users
Content-Type: application/json

{
    "id":123,
    "name": "John Doe",
    "password": "pass123",
    "role":"MECHANIC"
    
}


### PUT
PUT  http://localhost:8080/users/2
Content-Type: application/json

{
    "id":2,
    "name": "Sofie Castre",
    "password": "pass123",
    "role":"MECHANIC"
}


###

DELETE  http://localhost:8080/users/123